#!/bin/bash

f2py --overwrite-signature -m tslib -h tslib.pyf tslib.f95
#f2py -c -L/usr/local/lib -llapack tslib.pyf tslib.f90
#f2py -c --f90flags='-fopenmp' --opt='-O3' -lgomp tslib.pyf tslib.f90 ./lapack/*.f
#f2py -c --f90flags='-fopenmp' --opt='-O3 -fmax-stack-var-size=64000000 -cpp' -lgomp tslib.pyf tslib.f90 ./lapack/*.f
#f2py -c --fcompiler=gnu95 --opt='-O3 -ffast-math ' -lgomp tslib.pyf tslib.f90 ./lapack/*.f
#f2py -c --compiler=intel --opt='-O3 -ffast-math ' tslib.pyf tslib.f95 ./lapack/*.f
f2py -c --opt='-O3 -ffast-math ' -lgomp tslib.pyf tslib.f95 ./lapack/*.f
#gfortran -c -fPIC tslib.f90 ./lapack/*.f
#f2py tslib.f90 ./lapack/*.f tslib.pyf
#gfortran -c -O3 -fPIC tslib.f90 -o tslib.o
#gfortran -c -O3 -fPIC ./lapack/*.f
#gcc -c tslibmodule.c
#gcc -c fortranobject.c
#gfortran -o tslib.so -O3 -fPIC -shared -lgfortran tslib-f2pywrappers2.f90 tslib.f90 ./lapack/*.f
#f2py -c *.o -m tslib --build-dir ./bld tslib-f2pywrappers2.f90

cp tslib.so ../
