!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_tslib_indx (indxf2pywrap, ii, jj, np)
      use tslib, only : indx
      integer ii
      integer jj
      integer np
      integer indxf2pywrap
      indxf2pywrap = indx(ii, jj, np)
      end subroutine f2pywrap_tslib_indx
      subroutine f2pywrap_tslib_r_arr (r_arrf2pywrap, y, z, ny, nz)
      use tslib, only : r_arr
      integer ny
      integer nz
      real y(ny)
      real z(nz)
      real r_arrf2pywrap(ny*nz*(ny*nz+1)/2)
      r_arrf2pywrap = r_arr(y, z, ny, nz)
      end subroutine f2pywrap_tslib_r_arr
      
      subroutine f2pyinittslib(f2pysetupfunc)
      use tslib, only : nonieccoh
      use tslib, only : ieccoh
      interface 
      subroutine f2pywrap_tslib_indx (indxf2pywrap, indx, ii, jj, np)
      integer indx
      integer ii
      integer jj
      integer np
      integer indxf2pywrap
      end subroutine f2pywrap_tslib_indx 
      subroutine f2pywrap_tslib_r_arr (r_arrf2pywrap, r_arr, y, z, ny, n&
     &z)
      integer ny
      integer nz
      real y(ny)
      real z(nz)
      real r_arr(ny*nz*(ny*nz+1)/2)
      real r_arrf2pywrap(ny*nz*(ny*nz+1)/2)
      end subroutine f2pywrap_tslib_r_arr
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_tslib_indx,f2pywrap_tslib_r_arr,noniec&
     &coh,ieccoh)
      end subroutine f2pyinittslib


