/* File: tslibmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Wed Feb 19 08:58:58 2014
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include <stdarg.h>
#include "Python.h"
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *tslib_error;
static PyObject *tslib_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef struct {float r,i;} complex_float;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(tslib_error,errstring);\
    /*goto capi_fail;*/\
  } else 
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = tslib_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = tslib_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
  double d=0.0;
  if (double_from_pyobj(&d,obj,errmess)) {
    *v = (float)d;
    return 1;
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ indx ************************************/
static char doc_f2py_rout_tslib_tslib_indx[] = "\
Function signature:\n\
  indx = indx(ii,jj,np)\n\
Required arguments:\n"
"  ii : input int\n"
"  jj : input int\n"
"  np : input int\n"
"Return objects:\n"
"  indx : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_tslib_tslib_indx(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int indx = 0;
  int ii = 0;
  PyObject *ii_capi = Py_None;
  int jj = 0;
  PyObject *jj_capi = Py_None;
  int np = 0;
  PyObject *np_capi = Py_None;
  static char *capi_kwlist[] = {"ii","jj","np",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:tslib.tslib.indx",\
    capi_kwlist,&ii_capi,&jj_capi,&np_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable ii */
    f2py_success = int_from_pyobj(&ii,ii_capi,"tslib.tslib.indx() 1st argument (ii) can't be converted to int");
  if (f2py_success) {
  /* Processing variable np */
    f2py_success = int_from_pyobj(&np,np_capi,"tslib.tslib.indx() 3rd argument (np) can't be converted to int");
  if (f2py_success) {
  /* Processing variable indx */
  /* Processing variable jj */
    f2py_success = int_from_pyobj(&jj,jj_capi,"tslib.tslib.indx() 2nd argument (jj) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&indx,&ii,&jj,&np);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",indx);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of jj*/
  /* End of cleaning variable jj */
  /* End of cleaning variable indx */
  } /*if (f2py_success) of np*/
  /* End of cleaning variable np */
  } /*if (f2py_success) of ii*/
  /* End of cleaning variable ii */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of indx ********************************/

/*********************************** r_arr ***********************************/
static char doc_f2py_rout_tslib_tslib_r_arr[] = "\
Function signature:\n\
  r_arr = r_arr(y,z,[ny,nz])\n\
Required arguments:\n"
"  y : input rank-1 array('f') with bounds (ny)\n"
"  z : input rank-1 array('f') with bounds (nz)\n"
"Optional arguments:\n"
"  ny := len(y) input int\n"
"  nz := len(z) input int\n"
"Return objects:\n"
"  r_arr : rank-1 array('f') with bounds (ny*nz*(ny*nz+1)/2)";
/* #declfortranroutine# */
static PyObject *f2py_rout_tslib_tslib_r_arr(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *r_arr = NULL;
  npy_intp r_arr_Dims[1] = {-1};
  const int r_arr_Rank = 1;
  PyArrayObject *capi_r_arr_tmp = NULL;
  int capi_r_arr_intent = 0;
  float *y = NULL;
  npy_intp y_Dims[1] = {-1};
  const int y_Rank = 1;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  PyObject *y_capi = Py_None;
  float *z = NULL;
  npy_intp z_Dims[1] = {-1};
  const int z_Rank = 1;
  PyArrayObject *capi_z_tmp = NULL;
  int capi_z_intent = 0;
  PyObject *z_capi = Py_None;
  int ny = 0;
  PyObject *ny_capi = Py_None;
  int nz = 0;
  PyObject *nz_capi = Py_None;
  static char *capi_kwlist[] = {"y","z","ny","nz",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO|OO:tslib.tslib.r_arr",\
    capi_kwlist,&y_capi,&z_capi,&ny_capi,&nz_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable y */
  ;
  capi_y_intent |= F2PY_INTENT_IN;
  capi_y_tmp = array_from_pyobj(PyArray_FLOAT,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tslib_error,"failed in converting 1st argument `y' of tslib.tslib.r_arr to C/Fortran array" );
  } else {
    y = (float *)(capi_y_tmp->data);

  /* Processing variable z */
  ;
  capi_z_intent |= F2PY_INTENT_IN;
  capi_z_tmp = array_from_pyobj(PyArray_FLOAT,z_Dims,z_Rank,capi_z_intent,z_capi);
  if (capi_z_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tslib_error,"failed in converting 2nd argument `z' of tslib.tslib.r_arr to C/Fortran array" );
  } else {
    z = (float *)(capi_z_tmp->data);

  /* Processing variable r_arr */
  ;
  capi_r_arr_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_r_arr_tmp = array_from_pyobj(PyArray_FLOAT,r_arr_Dims,r_arr_Rank,capi_r_arr_intent,Py_None);
  if (capi_r_arr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tslib_error,"failed in converting hidden `r_arr' of tslib.tslib.r_arr to C/Fortran array" );
  } else {
    r_arr = (float *)(capi_r_arr_tmp->data);

  /* Processing variable ny */
  if (ny_capi == Py_None) ny = len(y); else
    f2py_success = int_from_pyobj(&ny,ny_capi,"tslib.tslib.r_arr() 1st keyword (ny) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(y)>=ny,"len(y)>=ny","1st keyword ny","r_arr:ny=%d",ny) {
  /* Processing variable nz */
  if (nz_capi == Py_None) nz = len(z); else
    f2py_success = int_from_pyobj(&nz,nz_capi,"tslib.tslib.r_arr() 2nd keyword (nz) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(z)>=nz,"len(z)>=nz","2nd keyword nz","r_arr:nz=%d",nz) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(r_arr,y,z,&ny,&nz);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_r_arr_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(z)>=nz)*/
  } /*if (f2py_success) of nz*/
  /* End of cleaning variable nz */
  } /*CHECKSCALAR(len(y)>=ny)*/
  } /*if (f2py_success) of ny*/
  /* End of cleaning variable ny */
  }  /*if (capi_r_arr_tmp == NULL) ... else of r_arr*/
  /* End of cleaning variable r_arr */
  if((PyObject *)capi_z_tmp!=z_capi) {
    Py_XDECREF(capi_z_tmp); }
  }  /*if (capi_z_tmp == NULL) ... else of z*/
  /* End of cleaning variable z */
  if((PyObject *)capi_y_tmp!=y_capi) {
    Py_XDECREF(capi_y_tmp); }
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of r_arr ********************************/

/********************************* nonieccoh *********************************/
static char doc_f2py_rout_tslib_tslib_nonieccoh[] = "\
Function signature:\n\
  nonieccoh(spec,phr,f,y,z,u,coef_a,coef_b,coefexp,ncore,[nf,ny,nz])\n\
Required arguments:\n"
"  spec : in/output rank-2 array('F') with bounds (ny*nz,nf + 1)\n"
"  phr : input rank-2 array('F') with bounds (ny*nz,nf)\n"
"  f : input rank-1 array('f') with bounds (nf)\n"
"  y : input rank-1 array('f') with bounds (ny)\n"
"  z : input rank-1 array('f') with bounds (nz)\n"
"  u : input rank-1 array('f') with bounds (ny*nz)\n"
"  coef_a : input float\n"
"  coef_b : input float\n"
"  coefexp : input float\n"
"  ncore : input int\n"
"Optional arguments:\n"
"  nf := (shape(spec,1)-1) input int\n"
"  ny := len(y) input int\n"
"  nz := len(z) input int";
/*  */
static PyObject *f2py_rout_tslib_tslib_nonieccoh(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(complex_float*,complex_float*,float*,float*,float*,float*,float*,float*,float*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  complex_float *spec = NULL;
  npy_intp spec_Dims[2] = {-1, -1};
  const int spec_Rank = 2;
  PyArrayObject *capi_spec_tmp = NULL;
  int capi_spec_intent = 0;
  PyObject *spec_capi = Py_None;
  complex_float *phr = NULL;
  npy_intp phr_Dims[2] = {-1, -1};
  const int phr_Rank = 2;
  PyArrayObject *capi_phr_tmp = NULL;
  int capi_phr_intent = 0;
  PyObject *phr_capi = Py_None;
  float *f = NULL;
  npy_intp f_Dims[1] = {-1};
  const int f_Rank = 1;
  PyArrayObject *capi_f_tmp = NULL;
  int capi_f_intent = 0;
  PyObject *f_capi = Py_None;
  float *y = NULL;
  npy_intp y_Dims[1] = {-1};
  const int y_Rank = 1;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  PyObject *y_capi = Py_None;
  float *z = NULL;
  npy_intp z_Dims[1] = {-1};
  const int z_Rank = 1;
  PyArrayObject *capi_z_tmp = NULL;
  int capi_z_intent = 0;
  PyObject *z_capi = Py_None;
  float *u = NULL;
  npy_intp u_Dims[1] = {-1};
  const int u_Rank = 1;
  PyArrayObject *capi_u_tmp = NULL;
  int capi_u_intent = 0;
  PyObject *u_capi = Py_None;
  float coef_a = 0;
  PyObject *coef_a_capi = Py_None;
  float coef_b = 0;
  PyObject *coef_b_capi = Py_None;
  float coefexp = 0;
  PyObject *coefexp_capi = Py_None;
  int ncore = 0;
  PyObject *ncore_capi = Py_None;
  int nf = 0;
  PyObject *nf_capi = Py_None;
  int ny = 0;
  PyObject *ny_capi = Py_None;
  int nz = 0;
  PyObject *nz_capi = Py_None;
  static char *capi_kwlist[] = {"spec","phr","f","y","z","u","coef_a","coef_b","coefexp","ncore","nf","ny","nz",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOO|OOO:tslib.tslib.nonieccoh",\
    capi_kwlist,&spec_capi,&phr_capi,&f_capi,&y_capi,&z_capi,&u_capi,&coef_a_capi,&coef_b_capi,&coefexp_capi,&ncore_capi,&nf_capi,&ny_capi,&nz_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable coefexp */
    f2py_success = float_from_pyobj(&coefexp,coefexp_capi,"tslib.tslib.nonieccoh() 9th argument (coefexp) can't be converted to float");
  if (f2py_success) {
  /* Processing variable coef_a */
    f2py_success = float_from_pyobj(&coef_a,coef_a_capi,"tslib.tslib.nonieccoh() 7th argument (coef_a) can't be converted to float");
  if (f2py_success) {
  /* Processing variable coef_b */
    f2py_success = float_from_pyobj(&coef_b,coef_b_capi,"tslib.tslib.nonieccoh() 8th argument (coef_b) can't be converted to float");
  if (f2py_success) {
  /* Processing variable ncore */
    f2py_success = int_from_pyobj(&ncore,ncore_capi,"tslib.tslib.nonieccoh() 10th argument (ncore) can't be converted to int");
  if (f2py_success) {
  /* Processing variable y */
  ;
  capi_y_intent |= F2PY_INTENT_IN;
  capi_y_tmp = array_from_pyobj(PyArray_FLOAT,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tslib_error,"failed in converting 4th argument `y' of tslib.tslib.nonieccoh to C/Fortran array" );
  } else {
    y = (float *)(capi_y_tmp->data);

  /* Processing variable z */
  ;
  capi_z_intent |= F2PY_INTENT_IN;
  capi_z_tmp = array_from_pyobj(PyArray_FLOAT,z_Dims,z_Rank,capi_z_intent,z_capi);
  if (capi_z_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tslib_error,"failed in converting 5th argument `z' of tslib.tslib.nonieccoh to C/Fortran array" );
  } else {
    z = (float *)(capi_z_tmp->data);

  /* Processing variable ny */
  if (ny_capi == Py_None) ny = len(y); else
    f2py_success = int_from_pyobj(&ny,ny_capi,"tslib.tslib.nonieccoh() 2nd keyword (ny) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(y)>=ny,"len(y)>=ny","2nd keyword ny","nonieccoh:ny=%d",ny) {
  /* Processing variable nz */
  if (nz_capi == Py_None) nz = len(z); else
    f2py_success = int_from_pyobj(&nz,nz_capi,"tslib.tslib.nonieccoh() 3rd keyword (nz) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(z)>=nz,"len(z)>=nz","3rd keyword nz","nonieccoh:nz=%d",nz) {
  /* Processing variable u */
  u_Dims[0]=ny*nz;
  capi_u_intent |= F2PY_INTENT_IN;
  capi_u_tmp = array_from_pyobj(PyArray_FLOAT,u_Dims,u_Rank,capi_u_intent,u_capi);
  if (capi_u_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tslib_error,"failed in converting 6th argument `u' of tslib.tslib.nonieccoh to C/Fortran array" );
  } else {
    u = (float *)(capi_u_tmp->data);

  /* Processing variable spec */
  spec_Dims[0]=ny*nz;
  capi_spec_intent |= F2PY_INTENT_INOUT;
  capi_spec_tmp = array_from_pyobj(PyArray_CFLOAT,spec_Dims,spec_Rank,capi_spec_intent,spec_capi);
  if (capi_spec_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tslib_error,"failed in converting 1st argument `spec' of tslib.tslib.nonieccoh to C/Fortran array" );
  } else {
    spec = (complex_float *)(capi_spec_tmp->data);

  /* Processing variable nf */
  if (nf_capi == Py_None) nf = (shape(spec,1)-1); else
    f2py_success = int_from_pyobj(&nf,nf_capi,"tslib.tslib.nonieccoh() 1st keyword (nf) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR((shape(spec,1)-1)==nf,"(shape(spec,1)-1)==nf","1st keyword nf","nonieccoh:nf=%d",nf) {
  /* Processing variable phr */
  phr_Dims[0]=ny*nz,phr_Dims[1]=nf;
  capi_phr_intent |= F2PY_INTENT_IN;
  capi_phr_tmp = array_from_pyobj(PyArray_CFLOAT,phr_Dims,phr_Rank,capi_phr_intent,phr_capi);
  if (capi_phr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tslib_error,"failed in converting 2nd argument `phr' of tslib.tslib.nonieccoh to C/Fortran array" );
  } else {
    phr = (complex_float *)(capi_phr_tmp->data);

  /* Processing variable f */
  f_Dims[0]=nf;
  capi_f_intent |= F2PY_INTENT_IN;
  capi_f_tmp = array_from_pyobj(PyArray_FLOAT,f_Dims,f_Rank,capi_f_intent,f_capi);
  if (capi_f_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tslib_error,"failed in converting 3rd argument `f' of tslib.tslib.nonieccoh to C/Fortran array" );
  } else {
    f = (float *)(capi_f_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(spec,phr,f,y,z,u,&coef_a,&coef_b,&coefexp,&ncore,&nf,&ny,&nz);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_f_tmp!=f_capi) {
    Py_XDECREF(capi_f_tmp); }
  }  /*if (capi_f_tmp == NULL) ... else of f*/
  /* End of cleaning variable f */
  if((PyObject *)capi_phr_tmp!=phr_capi) {
    Py_XDECREF(capi_phr_tmp); }
  }  /*if (capi_phr_tmp == NULL) ... else of phr*/
  /* End of cleaning variable phr */
  } /*CHECKSCALAR((shape(spec,1)-1)==nf)*/
  } /*if (f2py_success) of nf*/
  /* End of cleaning variable nf */
  if((PyObject *)capi_spec_tmp!=spec_capi) {
    Py_XDECREF(capi_spec_tmp); }
  }  /*if (capi_spec_tmp == NULL) ... else of spec*/
  /* End of cleaning variable spec */
  if((PyObject *)capi_u_tmp!=u_capi) {
    Py_XDECREF(capi_u_tmp); }
  }  /*if (capi_u_tmp == NULL) ... else of u*/
  /* End of cleaning variable u */
  } /*CHECKSCALAR(len(z)>=nz)*/
  } /*if (f2py_success) of nz*/
  /* End of cleaning variable nz */
  } /*CHECKSCALAR(len(y)>=ny)*/
  } /*if (f2py_success) of ny*/
  /* End of cleaning variable ny */
  if((PyObject *)capi_z_tmp!=z_capi) {
    Py_XDECREF(capi_z_tmp); }
  }  /*if (capi_z_tmp == NULL) ... else of z*/
  /* End of cleaning variable z */
  if((PyObject *)capi_y_tmp!=y_capi) {
    Py_XDECREF(capi_y_tmp); }
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
  } /*if (f2py_success) of ncore*/
  /* End of cleaning variable ncore */
  } /*if (f2py_success) of coef_b*/
  /* End of cleaning variable coef_b */
  } /*if (f2py_success) of coef_a*/
  /* End of cleaning variable coef_a */
  } /*if (f2py_success) of coefexp*/
  /* End of cleaning variable coefexp */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of nonieccoh ******************************/

/*********************************** ieccoh ***********************************/
static char doc_f2py_rout_tslib_tslib_ieccoh[] = "\
Function signature:\n\
  ieccoh(spec,phr,f,y,z,uhub,a,lc,ncore,[nf,ny,nz])\n\
Required arguments:\n"
"  spec : in/output rank-2 array('F') with bounds (ny*nz,nf + 1)\n"
"  phr : input rank-2 array('F') with bounds (ny*nz,nf)\n"
"  f : input rank-1 array('f') with bounds (nf)\n"
"  y : input rank-1 array('f') with bounds (ny)\n"
"  z : input rank-1 array('f') with bounds (nz)\n"
"  uhub : input float\n"
"  a : input float\n"
"  lc : input float\n"
"  ncore : input int\n"
"Optional arguments:\n"
"  nf := (shape(spec,1)-1) input int\n"
"  ny := len(y) input int\n"
"  nz := len(z) input int";
/*  */
static PyObject *f2py_rout_tslib_tslib_ieccoh(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(complex_float*,complex_float*,float*,float*,float*,float*,float*,float*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  complex_float *spec = NULL;
  npy_intp spec_Dims[2] = {-1, -1};
  const int spec_Rank = 2;
  PyArrayObject *capi_spec_tmp = NULL;
  int capi_spec_intent = 0;
  PyObject *spec_capi = Py_None;
  complex_float *phr = NULL;
  npy_intp phr_Dims[2] = {-1, -1};
  const int phr_Rank = 2;
  PyArrayObject *capi_phr_tmp = NULL;
  int capi_phr_intent = 0;
  PyObject *phr_capi = Py_None;
  float *f = NULL;
  npy_intp f_Dims[1] = {-1};
  const int f_Rank = 1;
  PyArrayObject *capi_f_tmp = NULL;
  int capi_f_intent = 0;
  PyObject *f_capi = Py_None;
  float *y = NULL;
  npy_intp y_Dims[1] = {-1};
  const int y_Rank = 1;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  PyObject *y_capi = Py_None;
  float *z = NULL;
  npy_intp z_Dims[1] = {-1};
  const int z_Rank = 1;
  PyArrayObject *capi_z_tmp = NULL;
  int capi_z_intent = 0;
  PyObject *z_capi = Py_None;
  float uhub = 0;
  PyObject *uhub_capi = Py_None;
  float a = 0;
  PyObject *a_capi = Py_None;
  float lc = 0;
  PyObject *lc_capi = Py_None;
  int ncore = 0;
  PyObject *ncore_capi = Py_None;
  int nf = 0;
  PyObject *nf_capi = Py_None;
  int ny = 0;
  PyObject *ny_capi = Py_None;
  int nz = 0;
  PyObject *nz_capi = Py_None;
  static char *capi_kwlist[] = {"spec","phr","f","y","z","uhub","a","lc","ncore","nf","ny","nz",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO|OOO:tslib.tslib.ieccoh",\
    capi_kwlist,&spec_capi,&phr_capi,&f_capi,&y_capi,&z_capi,&uhub_capi,&a_capi,&lc_capi,&ncore_capi,&nf_capi,&ny_capi,&nz_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
    f2py_success = float_from_pyobj(&a,a_capi,"tslib.tslib.ieccoh() 7th argument (a) can't be converted to float");
  if (f2py_success) {
  /* Processing variable lc */
    f2py_success = float_from_pyobj(&lc,lc_capi,"tslib.tslib.ieccoh() 8th argument (lc) can't be converted to float");
  if (f2py_success) {
  /* Processing variable ncore */
    f2py_success = int_from_pyobj(&ncore,ncore_capi,"tslib.tslib.ieccoh() 9th argument (ncore) can't be converted to int");
  if (f2py_success) {
  /* Processing variable uhub */
    f2py_success = float_from_pyobj(&uhub,uhub_capi,"tslib.tslib.ieccoh() 6th argument (uhub) can't be converted to float");
  if (f2py_success) {
  /* Processing variable y */
  ;
  capi_y_intent |= F2PY_INTENT_IN;
  capi_y_tmp = array_from_pyobj(PyArray_FLOAT,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tslib_error,"failed in converting 4th argument `y' of tslib.tslib.ieccoh to C/Fortran array" );
  } else {
    y = (float *)(capi_y_tmp->data);

  /* Processing variable z */
  ;
  capi_z_intent |= F2PY_INTENT_IN;
  capi_z_tmp = array_from_pyobj(PyArray_FLOAT,z_Dims,z_Rank,capi_z_intent,z_capi);
  if (capi_z_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tslib_error,"failed in converting 5th argument `z' of tslib.tslib.ieccoh to C/Fortran array" );
  } else {
    z = (float *)(capi_z_tmp->data);

  /* Processing variable ny */
  if (ny_capi == Py_None) ny = len(y); else
    f2py_success = int_from_pyobj(&ny,ny_capi,"tslib.tslib.ieccoh() 2nd keyword (ny) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(y)>=ny,"len(y)>=ny","2nd keyword ny","ieccoh:ny=%d",ny) {
  /* Processing variable nz */
  if (nz_capi == Py_None) nz = len(z); else
    f2py_success = int_from_pyobj(&nz,nz_capi,"tslib.tslib.ieccoh() 3rd keyword (nz) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(z)>=nz,"len(z)>=nz","3rd keyword nz","ieccoh:nz=%d",nz) {
  /* Processing variable spec */
  spec_Dims[0]=ny*nz;
  capi_spec_intent |= F2PY_INTENT_INOUT;
  capi_spec_tmp = array_from_pyobj(PyArray_CFLOAT,spec_Dims,spec_Rank,capi_spec_intent,spec_capi);
  if (capi_spec_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tslib_error,"failed in converting 1st argument `spec' of tslib.tslib.ieccoh to C/Fortran array" );
  } else {
    spec = (complex_float *)(capi_spec_tmp->data);

  /* Processing variable nf */
  if (nf_capi == Py_None) nf = (shape(spec,1)-1); else
    f2py_success = int_from_pyobj(&nf,nf_capi,"tslib.tslib.ieccoh() 1st keyword (nf) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR((shape(spec,1)-1)==nf,"(shape(spec,1)-1)==nf","1st keyword nf","ieccoh:nf=%d",nf) {
  /* Processing variable phr */
  phr_Dims[0]=ny*nz,phr_Dims[1]=nf;
  capi_phr_intent |= F2PY_INTENT_IN;
  capi_phr_tmp = array_from_pyobj(PyArray_CFLOAT,phr_Dims,phr_Rank,capi_phr_intent,phr_capi);
  if (capi_phr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tslib_error,"failed in converting 2nd argument `phr' of tslib.tslib.ieccoh to C/Fortran array" );
  } else {
    phr = (complex_float *)(capi_phr_tmp->data);

  /* Processing variable f */
  f_Dims[0]=nf;
  capi_f_intent |= F2PY_INTENT_IN;
  capi_f_tmp = array_from_pyobj(PyArray_FLOAT,f_Dims,f_Rank,capi_f_intent,f_capi);
  if (capi_f_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(tslib_error,"failed in converting 3rd argument `f' of tslib.tslib.ieccoh to C/Fortran array" );
  } else {
    f = (float *)(capi_f_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(spec,phr,f,y,z,&uhub,&a,&lc,&ncore,&nf,&ny,&nz);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_f_tmp!=f_capi) {
    Py_XDECREF(capi_f_tmp); }
  }  /*if (capi_f_tmp == NULL) ... else of f*/
  /* End of cleaning variable f */
  if((PyObject *)capi_phr_tmp!=phr_capi) {
    Py_XDECREF(capi_phr_tmp); }
  }  /*if (capi_phr_tmp == NULL) ... else of phr*/
  /* End of cleaning variable phr */
  } /*CHECKSCALAR((shape(spec,1)-1)==nf)*/
  } /*if (f2py_success) of nf*/
  /* End of cleaning variable nf */
  if((PyObject *)capi_spec_tmp!=spec_capi) {
    Py_XDECREF(capi_spec_tmp); }
  }  /*if (capi_spec_tmp == NULL) ... else of spec*/
  /* End of cleaning variable spec */
  } /*CHECKSCALAR(len(z)>=nz)*/
  } /*if (f2py_success) of nz*/
  /* End of cleaning variable nz */
  } /*CHECKSCALAR(len(y)>=ny)*/
  } /*if (f2py_success) of ny*/
  /* End of cleaning variable ny */
  if((PyObject *)capi_z_tmp!=z_capi) {
    Py_XDECREF(capi_z_tmp); }
  }  /*if (capi_z_tmp == NULL) ... else of z*/
  /* End of cleaning variable z */
  if((PyObject *)capi_y_tmp!=y_capi) {
    Py_XDECREF(capi_y_tmp); }
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
  } /*if (f2py_success) of uhub*/
  /* End of cleaning variable uhub */
  } /*if (f2py_success) of ncore*/
  /* End of cleaning variable ncore */
  } /*if (f2py_success) of lc*/
  /* End of cleaning variable lc */
  } /*if (f2py_success) of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of ieccoh *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_tslib_def[] = {
  {"indx",-1,{{-1}},0,NULL,(void *)f2py_rout_tslib_tslib_indx,doc_f2py_rout_tslib_tslib_indx},
  {"r_arr",-1,{{-1}},0,NULL,(void *)f2py_rout_tslib_tslib_r_arr,doc_f2py_rout_tslib_tslib_r_arr},
  {"nonieccoh",-1,{{-1}},0,NULL,(void *)f2py_rout_tslib_tslib_nonieccoh,doc_f2py_rout_tslib_tslib_nonieccoh},
  {"ieccoh",-1,{{-1}},0,NULL,(void *)f2py_rout_tslib_tslib_ieccoh,doc_f2py_rout_tslib_tslib_ieccoh},
  {NULL}
};

static void f2py_setup_tslib(char *indx,char *r_arr,char *nonieccoh,char *ieccoh) {
  int i_f2py=0;
  f2py_tslib_def[i_f2py++].data = indx;
  f2py_tslib_def[i_f2py++].data = r_arr;
  f2py_tslib_def[i_f2py++].data = nonieccoh;
  f2py_tslib_def[i_f2py++].data = ieccoh;
}
extern void F_FUNC(f2pyinittslib,F2PYINITTSLIB)(void (*)(char *,char *,char *,char *));
static void f2py_init_tslib(void) {
  F_FUNC(f2pyinittslib,F2PYINITTSLIB)(f2py_setup_tslib);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "tslib",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyObject *PyInit_tslib(void) {
#else
#define RETVAL
PyMODINIT_FUNC inittslib(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = tslib_module = PyModule_Create(&moduledef);
#else
  m = tslib_module = Py_InitModule("tslib", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module tslib (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'tslib' is auto-generated with f2py (version:2).\nFunctions:\n"
"Fortran 90/95 modules:\n""  tslib --- indx(),r_arr(),nonieccoh(),ieccoh()"".");
  PyDict_SetItemString(d, "__doc__", s);
  tslib_error = PyErr_NewException ("tslib.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));




/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "tslib", PyFortranObject_New(f2py_tslib_def,f2py_init_tslib));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"tslib");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
