# The setup script for installing TurbGen
from numpy.distutils.core import setup, Extension
from TurbGen import _version as ver

setup(name='TurbGen',
      version=ver.__version__,
      description='A python turbulence generator tool modeled after TurbSim',
      author='Levi Kilcher',
      author_email='levi.kilcher@nrel.gov',
      url='http://lkilcher.github.io/TurbGen',
      packages=[ver.pkg_name,
                ver.pkg_name + '.io',
                ver.pkg_name + '.gui',
                ver.pkg_name + '.plot',
                ver.pkg_name + '.cohereModels',
                ver.pkg_name + '.phaseModels',
                ver.pkg_name + '.profModels',
                ver.pkg_name + '.runInput',
                ver.pkg_name + '.specModels',
                ver.pkg_name + '.stressModels', ],
      requires=['numpy', ],
      data_files=[
          ('TurbGen/io/templates',
           ['TurbGen/io/templates/sum',
            'TurbGen/io/templates/inp', ]),
          ('TurbGen/gui/default_inputs',
           ['TurbGen/gui/default_inputs/RIVER.inp',
            'TurbGen/gui/default_inputs/TIDAL.inp',
            'TurbGen/gui/default_inputs/WIND.inp',
            'TurbGen/gui/default_inputs/WIND_IEC.inp', ]),
      ],
      scripts=['TurbGen_script.py', ],
      ext_modules=[Extension('TurbGen.tslib',
                             sources=['TurbGen/tslib/tslib.pyf',
                                      'TurbGen/tslib/tslib.f95',
                                      'TurbGen/tslib/lapack/lsame.f',
                                      'TurbGen/tslib/lapack/sdot.f',
                                      'TurbGen/tslib/lapack/spptrf.f',
                                      'TurbGen/tslib/lapack/sscal.f',
                                      'TurbGen/tslib/lapack/sspr.f',
                                      'TurbGen/tslib/lapack/stpsv.f',
                                      'TurbGen/tslib/lapack/xerbla.f', ],
                             extra_link_args=['-lgomp'],
                             )],
      )
